JAVAC = javac
JAVA = java
JAVAC_FLAGS = -d ./classes/
JAVAC_CP = -cp "./lib/*"
JAVA_SRC = ./src/Stream.java ./src/StreamServer.java ./src/StreamConsole.java

default:
	$(JAVAC) $(JAVAC_FLAGS) $(JAVAC_CP) $(JAVA_SRC)

