JAVAC = javac
JAVA = java
JAVAC_FLAGS = -d ./classes/ -verbose
JAVAC_CP = -cp "C:/cygwin64/home/beltonzhong/Stream/java/lib/*"
JAVA_SRC = ./src/Stream.java ./src/StreamServer.java ./src/StreamConsole.java

default:
	$(JAVAC) $(JAVAC_FLAGS) $(JAVAC_CP) $(JAVA_SRC)

